### ISSUE TITLE
Unknown error

### ISSUE THREAD

**Issue by diplopito** [tporadowski/rejson#4]
Hi Tomasz,

Suddenly ReJSON stopped working. I copied the ReJSON.dll in the same folder as Redis but seems that it is not loading. When I try a simple "JSON.SET", it's reporting:

```
(error) ERR unknown command `JSON.SET`, with args beginning with `test`, `.`, `{"hello": "world"}`
```
Any idea of which could be the issue? I"m using Redis 5.0.10 and ReJSON 1.0.6, both on Win 10 Pro.

Thanks!

**Comment by tporadowski** [comment]
Please make sure you have it specified in the config file to be loaded. Is there anything specific in Redis' log file/output on console?

**Comment by diplopito** [comment]
That was it: I did a fresh installation and didn't add `loadmodule` to the service-conf file. Thanks Tomasz! I"m using it even from within WSL (Ubuntu 20.04) and it works fine.
